/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sauces.vista;

import com.sauces.controlador.Controlador;
import com.sauces.modelo.Empleado;
import com.sauces.modelo.dniExepcion;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author daw1
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grouprd = new javax.swing.ButtonGroup();
        selectorFicheros = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tdni = new javax.swing.JTextField();
        tnombre = new javax.swing.JTextField();
        ttipo = new javax.swing.JComboBox<>();
        tsalario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tingresos = new javax.swing.JTextField();
        btnborrar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        thoras = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        lista_de_empleados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaEmpleados = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        rddni = new javax.swing.JRadioButton();
        rdnombre = new javax.swing.JRadioButton();
        rdingresos = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        abrir = new javax.swing.JMenuItem();
        guardar = new javax.swing.JMenuItem();
        Empleado = new javax.swing.JMenu();
        nuevo = new javax.swing.JMenuItem();
        buscar = new javax.swing.JMenuItem();

        selectorFicheros.setCurrentDirectory(new java.io.File("D:\\OUTMANE\\DAWPROJECTS\\SistemaNominas\\src\\main\\java\\com\\suaces"));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Empleado"));

        jLabel1.setText("DNI :");

        jLabel2.setText("Nombre :");

        jLabel3.setText("Tipo :");

        jLabel4.setText("Salario :");

        ttipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fijo", "Eventual" }));

        jLabel5.setText("INGRESOS");

        btnborrar.setText("BORRAR");
        btnborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarActionPerformed(evt);
            }
        });

        btnmodificar.setText("MODIFICAR");

        jLabel7.setText("Horas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tnombre)
                            .addComponent(tdni, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ttipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tsalario)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tingresos, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 9, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(thoras, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ttipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tsalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(thoras, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tingresos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnborrar)
                    .addComponent(btnmodificar))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        lista_de_empleados.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de empleados"));

        EpleadoTM=new EmpleadoTableModel();
        TablaEmpleados.setModel(EpleadoTM);
        jScrollPane1.setViewportView(TablaEmpleados);

        jButton3.setText("Listar empleados");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listar_empleados(evt);
            }
        });

        jLabel6.setText("ORDEN DEL LISTADO :");

        grouprd.add(rddni);
        rddni.setSelected(true);
        rddni.setText("DNI");
        rddni.setName(""); // NOI18N

        grouprd.add(rdnombre);
        rdnombre.setText("NOMBRE");
        rdnombre.setName(""); // NOI18N

        grouprd.add(rdingresos);
        rdingresos.setText("INGRESOS");
        rdingresos.setName(""); // NOI18N

        javax.swing.GroupLayout lista_de_empleadosLayout = new javax.swing.GroupLayout(lista_de_empleados);
        lista_de_empleados.setLayout(lista_de_empleadosLayout);
        lista_de_empleadosLayout.setHorizontalGroup(
            lista_de_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lista_de_empleadosLayout.createSequentialGroup()
                .addGroup(lista_de_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lista_de_empleadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(lista_de_empleadosLayout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(lista_de_empleadosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6)
                .addGap(65, 65, 65)
                .addComponent(rddni)
                .addGap(39, 39, 39)
                .addComponent(rdnombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdingresos)
                .addContainerGap(252, Short.MAX_VALUE))
        );
        lista_de_empleadosLayout.setVerticalGroup(
            lista_de_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lista_de_empleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(lista_de_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rddni)
                    .addComponent(rdnombre)
                    .addComponent(rdingresos))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        Archivo.setText("Archivo");

        abrir.setText("Abrir");
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });
        Archivo.add(abrir);

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        Archivo.add(guardar);

        jMenuBar1.add(Archivo);

        Empleado.setText("Empleado");

        nuevo.setText("Nuevo");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearEmpleado(evt);
            }
        });
        Empleado.add(nuevo);

        buscar.setText("Buscar...");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        Empleado.add(buscar);

        jMenuBar1.add(Empleado);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lista_de_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lista_de_empleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearEmpleado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearEmpleado
        if (this.dialogo.mostarar() == DialogoEmpleado.ACEPATR) {
            this.tdni.setText(dialogo.getDni());
            this.tnombre.setText(dialogo.getNombre());
            this.tsalario.setText((dialogo.getSalario()).toString());
            this.ttipo.setSelectedItem(dialogo.getTipo());
            this.thoras.setValue(dialogo.getHorass());
            controlador.crearEmpleado();
            this.actualizarTabla();
        }

    }//GEN-LAST:event_CrearEmpleado

    private void Listar_empleados(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Listar_empleados
        controlador.listarEmpleados();
    }//GEN-LAST:event_Listar_empleados

    private void btnborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarActionPerformed
        // TODO add your handling code here:
        if(this.tDni)
        if (JOptionPane.showConfirmDialog(this, "¿Estas seguro?") == JOptionPane.OK_OPTION) {
            try {
                controlador.eliminarEmpleado();
                limpiarCampos();
            } catch (dniExepcion ex) {
                Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.actualizarTabla();
        }
    }//GEN-LAST:event_btnborrarActionPerformed

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
        // TODO add your handling code here:

        if (this.selectorFicheros.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            controlador.cargarEmpleados();
        }
    }//GEN-LAST:event_abrirActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        String dni = JOptionPane.showInputDialog(this, "Introduzca El empleado a buscar");
        if (dni != null) {
            try {
                limpiarCampos();
                mostrarDni(dni);
                controlador.buscarEmpleado();
            } catch (dniExepcion ex) {
                Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        tnombre.setEnabled(false);
        tsalario.setEnabled(false);
        ttipo.setEnabled(false);
        tingresos.setEnabled(false);
        thoras.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        if (this.selectorFicheros.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            controlador.guardarEmpleados();
        }
    }//GEN-LAST:event_guardarActionPerformed
    /*  public void tablechange()() {
        int fila = TablaEmpleados.getSelectedRow();
        if (fila >= 0) {
            tdni.setText((String) TablaEmpleados.getValueAt(fila, 0));
            tnombre.setText((String) TablaEmpleados.getValueAt(fila, 1));
            tsalario.setText(TablaEmpleados.getValueAt(fila, 2).toString());
        }
    }
}*/
    public void actualizarTabla() {
        this.TablaEmpleados.revalidate();
    }

    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }

    public String getTipo() {
        return this.ttipo.getSelectedItem().toString();
    }

    public String getDni() {
        return this.tdni.getText();
    }

    public String getNombre() {
        return this.tnombre.getText();
    }

    public float getSalario() {
        return Float.parseFloat(this.tsalario.getText());
    }

    public float getIngresos() {
        return Integer.parseInt(this.tingresos.getText());
    }

    public int getHoras() {
        return (int) this.thoras.getValue();
    }

    public String getArchivo() {
        String nombre = selectorFicheros.getSelectedFile().getAbsolutePath();
        return nombre;
    }

    public String getOrden() {
        this.rddni.getText();
        this.rdnombre.getText();
        this.rdingresos.getText();

        return null;
    }

    public void mostrarTipo(String tipo) {

        this.ttipo.setSelectedItem(tipo);
    }

    public void mostrarDni(String dni) {
        this.tdni.setText(dni);
    }

    public void mostrarNombre(String nombre) {
        this.tnombre.setText(nombre);
    }

    public void mostrarSalario(float salario) {

        this.tsalario.setText(Float.toString(salario));
    }

    public void mostrarHoras(int horas) {
        this.thoras.setValue(Integer.toString(horas));
    }

    public void mostrarIngresos(float ingresos) {
        this.tingresos.setText(Float.toString(ingresos));
    }

    public void listarEmpleados(List<Empleado> listado) {
        EpleadoTM.setListado(listado);
        actualizarTabla();
    }

    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    public boolean solicitarConfirmacion() {
        return false;
    }

    public void limpiarCampos() {
        this.tdni.setText("");
        this.tnombre.setText("");
        this.tsalario.setText("");
        this.ttipo.setSelectedIndex(0);
        this.tingresos.setText("");
    }

    public void mostrar() {
        setVisible(true);

    }

    private Controlador controlador;

    private DialogoEmpleado dialogo = new DialogoEmpleado(this, true);

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Archivo;
    private javax.swing.JMenu Empleado;
    public EmpleadoTableModel EpleadoTM;
    private javax.swing.JTable TablaEmpleados;
    private javax.swing.JMenuItem abrir;
    private javax.swing.JButton btnborrar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JMenuItem buscar;
    private javax.swing.ButtonGroup grouprd;
    private javax.swing.JMenuItem guardar;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel lista_de_empleados;
    private javax.swing.JMenuItem nuevo;
    private javax.swing.JRadioButton rddni;
    private javax.swing.JRadioButton rdingresos;
    private javax.swing.JRadioButton rdnombre;
    private javax.swing.JFileChooser selectorFicheros;
    private javax.swing.JTextField tdni;
    private javax.swing.JSpinner thoras;
    private javax.swing.JTextField tingresos;
    private javax.swing.JTextField tnombre;
    private javax.swing.JTextField tsalario;
    private javax.swing.JComboBox<String> ttipo;
    // End of variables declaration//GEN-END:variables
}
